# Usa l'immagine ufficiale di Nginx con la versione 1.27.3
FROM nginx:1.27.3-alpine

# Copia i file statici nella directory di Nginx
COPY . /usr/share/nginx/html

# Esponi la porta 80 per servire i file
EXPOSE 80
