version: '3'
services:
  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db/isyrent_db
    depends_on:
      - db

  db:
    build:
      context: ./Database
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: isyrent_db
    ports:
      - "3306:3306"
